// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SalahGuardApi.Data;

#nullable disable

namespace SalahGuardApi.Migrations;

[DbContext(typeof(SalahGuardDbContext))]
partial class SalahGuardDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

        modelBuilder.Entity("SalahGuardApi.Models.DndSession", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("DurationMinutes").HasColumnType("INTEGER");
            b.Property<DateTime>("EndTime").HasColumnType("TEXT");
            b.Property<string>("PrayerName").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<DateTime>("StartTime").HasColumnType("TEXT");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("PrayerName");
            b.HasIndex("StartTime");
            b.HasIndex("PrayerName", "StartTime");
            b.ToTable("DndSessions");
        });

        modelBuilder.Entity("SalahGuardApi.Models.Prayer", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("ActiveDays").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("ArabicName").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<int>("DurationMinutes").HasColumnType("INTEGER");
            b.Property<bool>("IsEnabled").HasColumnType("INTEGER");
            b.Property<string>("Name").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
            b.Property<TimeSpan>("ScheduledTime").HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Prayers");
        });

        modelBuilder.Entity("SalahGuardApi.Models.RefreshToken", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<string>("DeviceId").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<DateTime>("ExpiresAt").HasColumnType("TEXT");
            b.Property<bool>("IsRevoked").HasColumnType("INTEGER");
            b.Property<DateTime?>("RevokedAt").HasColumnType("TEXT");
            b.Property<string>("TokenHash").IsRequired().HasMaxLength(512).HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("DeviceId");
            b.HasIndex("TokenHash").IsUnique();
            b.ToTable("RefreshTokens");
        });

        modelBuilder.Entity("SalahGuardApi.Models.UserSettings", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<bool>("DarkMode").HasColumnType("INTEGER");
            b.Property<bool>("IsGloballyActive").HasColumnType("INTEGER");
            b.Property<bool>("ShowLiftedNotification").HasColumnType("INTEGER");
            b.Property<bool>("SilentNotificationOnStart").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.ToTable("UserSettings");
        });
#pragma warning restore 612, 618
    }
}
